# -*- coding: utf-8 -*-
"""Module 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x2Z5p7r3L2VXnI0b7-hQtVQpFWJvz8_0
"""

import networkx as nx

# Load the downloaded friendship data.
G = nx.read_edgelist("facebook_combined.txt.gz", nodetype=int)

# Find the three users with the most direct connections.
centrality = nx.degree_centrality(G)
top_three = sorted(centrality, key=centrality.get, reverse=True)[:3]

for node in top_three:
    print(
        f"User {node}: {G.degree(node):,} friends, "
        f"centrality = {centrality[node]:.4f}"
    )

# Count their combined audience without double-counting friends.
audience = set()
for node in top_three:
    audience.update(G.neighbors(node))

audience.difference_update(top_three)
print(f"\nCombined audience: {len(audience):,} users")

# Check the graph against Stanford's published totals.
assert G.number_of_nodes() == 4039
assert G.number_of_edges() == 88234
assert nx.number_of_selfloops(G) == 0
assert nx.is_connected(G)
assert sum(dict(G.degree()).values()) == 2 * G.number_of_edges()